language: rust
cache: cargo
before_script:
  - cargo install -f rustfmt --vers 0.7.1  # the 0.8.0 is buggy, for the moment we fix the version
  - export PATH=$PATH:$HOME/.cargo/bin
rust:
  - stable
  - beta
  - nightly

script:
  - cargo fmt -- --write-mode=diff
  - cargo test
  - sudo apt-get -qq update
  - sudo apt-get install -y aspell aspell-fr
  - cd tests/data
  - ../../target/release/ruspell -i stops.txt -r rules.csv -o stops_out.txt -c conf/config-fr_idf.yml
  - diff stops_out.txt stops_out_ref.txt

matrix:
  allow_failures:
    - rust: nightly
