language: rust
addons:
  apt:
    packages:
      - aspell-fr
cache: cargo
rust:
  - stable
  - beta
  - nightly
env:
  - RUN=TEST
script:
  - cargo test
  - sh tests/fr-idf.sh

matrix:
  include:
    - rust: nightly
      env: RUN=RUSTFMT
      before_script: rustup component add rustfmt-preview
      script: cargo fmt --all -- --write-mode diff
  allow_failures:
    - rust: nightly
      env: RUN=TEST
